### ISSUE TITLE
scala version fail？

### ISSUE THREAD

**Issue by jinleileiking** [arnobroekhof/kafka-http-metrics-reporter#2]
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc

**Comment by sumitm-iiit** [comment]
Any updates on the fix for this issue ?

**Comment by arnobroekhof** [comment]
Unable to reproduce, can you please be more specific?

**Comment by arnobroekhof** [comment]
Updated library to kafka 2.12 and version 0.10.2.0
